# Starter pipeline


trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:
- task: AzureResourceGroupDeployment@2
  inputs:
    azureSubscription: 'Visual Studio Premium with MSDN(f0ab3975-e90c-4784-9c8b-93c2fec11966)'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'BuildLibrary'
    location: 'East US'
    templateLocation: 'Linked artifact'
    csmFile: 'DeploymentFiles/OpenCode'
    deploymentMode: 'Incremental'


