# Starter pipeline





trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:
- task: AzureResourceGroupDeployment@2
  inputs:
    azureSubscription: 'Visual Studio Premium with MSDN(f0ab3975-e90c-4784-9c8b-93c2fec11966)'
    action: 'Select Resource Group'
    resourceGroupName: 'BuildLibrary'
    outputVariable: 'DeployOpneCode'
- task: VSTest@2
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: '**\OpenCode.Tests\bin\$(BuildConfiguration)\**\*test*.dll
      !**\xunit.runner.visualstudio.testadapter.dll
      !**\xunit.runner.visualstudio.dotnetcore.testadapter.dll'
    searchFolder: '$(System.DefaultWorkingDirectory)'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
- task: VSBuild@1
  inputs:
    solution: '**\*.sln'
    vsVersion: '15.0'

