# Starter pipeline

  inputs:
    testSelector: 'testPlan'
    testPlan: '8'
    testSuite: '{

        "id": 9,

        "name": "Visual Studio Test",

        "plan": {

          "id": "8",

          "name": "8"

        },

        "testCaseCount": 0,

        "inheritDefaultConfigurations": false,

        "lastUpdatedDate": "0001-01-01T00:00:00",

        "text": "Visual Studio Test"

      }'
    testConfiguration: '1'
    searchFolder: '$(System.DefaultWorkingDirectory)'


trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
