# Starter pipeline


trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:
- task: AzureResourceGroupDeployment@2
  inputs:
    azureSubscription: 'Windows Azure  MSDN - Visual Studio Premium(2c7f00ce-1c20-464c-85ef-26afbbd7a416)'
    action: 'Select Resource Group'
    resourceGroupName: 'Default-Web-WestUS'


