
GET https://pkgs.dev.azure.com/navneethegde/OpenCode/_apis/packaging/feeds/QAFeed/nuget/packages/OpenCode/versions/3.0.17?api-version=7.1 HTTP/1.1
Content-Type: application/json

###
# PROMOT TO PRERELEASE

PATCH https://pkgs.dev.azure.com/navneethegde/OpenCode/_apis/packaging/feeds/QAFeed/nuget/packages/OpenCode/versions/3.0.18-Testfeature.1?api-version=7.1 HTTP/1.1
Content-Type:  application/json
Authorization:  Basic UpBVElOLTF1T2RnWXozc0tyZmlGcmtwLWpZbFQ5R1c1YXZKTFVYb040QUxYQUtzeDZ3TGNCVXNBSUdYYzVhaHhlOGR5Y0M2VUEtSGJ

{
  "views" : {
    "op": "add",
    "path": "/views/-",
    "value": "Prerelease"
  }
}


